version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/code
    command: sh -c "cd app && uvicorn main:app --host 0.0.0.0"
    ports:
      - "8080:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: 'postgres:16-alpine'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=tracker
      - POSTGRES_PASSWORD=masterkey
      - POSTGRES_USER=admin
volumes:
    postgres_data: