services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
      image: 'postgres:16-alpine'
      restart: always
      user: postgres
      secrets:
        - db-password
      volumes:
        - db_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_DB=tracker
        - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
        - POSTGRES_USER=postgres
      ports:
        - 5437:5432
      healthcheck:
        test: [ "CMD", "pg_isready" ]
        interval: 10s
        timeout: 5s
        retries: 5
volumes:
  db_data:
secrets:
  db-password:
    file: app/db/password.txt